[pytest]
asyncio_mode = auto
pythonpath = pc-agent
filterwarnings =
    ignore::DeprecationWarning:pkg_resources
    ignore::DeprecationWarning:google.rpc
    ignore::RuntimeWarning:pydantic
    ignore::RuntimeWarning
