"""sync_schema_models

Revision ID: ac22b0d428d0
Revises: 0009_dg_add_color_parent
Create Date: 2026-02-23 15:37:38.990792+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac22b0d428d0'
down_revision: Union[str, None] = '0009_dg_add_color_parent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.alter_column('device_groups', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('devices', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'last_status',
               existing_type=postgresql.ENUM('online', 'offline', 'busy', 'error', 'maintenance', name='device_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ldplayer_instances', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ldplayer_instances', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_ldplayer_instances_org_id'), 'ldplayer_instances', ['org_id'], unique=False)
    op.drop_column('ldplayer_instances', 'instance_name')
    op.drop_column('ldplayer_instances', 'adb_port')
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_column('organizations', 'plan')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'meta')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_org_id'), 'refresh_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('script_versions', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('script_versions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_script_versions_org_id'), 'script_versions', ['org_id'], unique=False)
    op.alter_column('scripts', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scripts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_batches', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'partial', 'failed', 'cancelled', name='task_batch_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_batches', 'total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_batches', 'succeeded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_batches', 'failed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_batches', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_task_batches_script_id'), 'task_batches', ['script_id'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('queued', 'assigned', 'running', 'completed', 'failed', 'timeout', 'cancelled', name='task_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tasks_script_id'), 'tasks', ['script_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'mfa_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.alter_column('vpn_peers', 'device_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('vpn_peers', 'public_key',
               existing_type=sa.VARCHAR(length=44),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'allowed_ips',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vpn_peers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('FREE', 'ASSIGNED', 'ERROR', name='vpn_peer_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vpn_peers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('vpn_peers_device_id_key', 'vpn_peers', type_='unique')
    op.create_index(op.f('ix_vpn_peers_device_id'), 'vpn_peers', ['device_id'], unique=True)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('webhooks', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhooks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workstations', 'is_online',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workstations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('workstations', 'last_seen')
    op.drop_column('workstations', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workstations', sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('workstations', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('workstations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('workstations', 'is_online',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('webhooks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('webhooks', 'failure_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('webhooks', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('webhooks', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('ix_vpn_peers_device_id'), table_name='vpn_peers')
    op.create_unique_constraint('vpn_peers_device_id_key', 'vpn_peers', ['device_id'])
    op.alter_column('vpn_peers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'status',
               existing_type=sa.Enum('FREE', 'ASSIGNED', 'ERROR', name='vpn_peer_status', native_enum=False),
               server_default=sa.text("'assigned'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'allowed_ips',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'0.0.0.0/0'::character varying"),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'public_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=44),
               existing_nullable=False)
    op.alter_column('vpn_peers', 'device_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('users', 'mfa_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'viewer'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_script_id'), table_name='tasks')
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('tasks', 'timeout_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('300'),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('queued', 'assigned', 'running', 'completed', 'failed', 'timeout', 'cancelled', name='task_status_enum'),
               server_default=sa.text("'queued'::task_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_task_batches_script_id'), table_name='task_batches')
    op.alter_column('task_batches', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('task_batches', 'failed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_batches', 'succeeded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_batches', 'total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_batches', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'partial', 'failed', 'cancelled', name='task_batch_status_enum'),
               server_default=sa.text("'pending'::task_batch_status_enum"),
               existing_nullable=False)
    op.alter_column('scripts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('scripts', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_script_versions_org_id'), table_name='script_versions')
    op.alter_column('script_versions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('script_versions', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_org_id'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('organizations', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('plan', sa.VARCHAR(length=50), server_default=sa.text("'free'::character varying"), autoincrement=False, nullable=False))
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('ldplayer_instances', sa.Column('adb_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ldplayer_instances', sa.Column('instance_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ldplayer_instances_org_id'), table_name='ldplayer_instances')
    op.alter_column('ldplayer_instances', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ldplayer_instances', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'stopped'::character varying"),
               existing_nullable=False)
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('devices', 'last_status',
               existing_type=postgresql.ENUM('online', 'offline', 'busy', 'error', 'maintenance', name='device_status_enum'),
               server_default=sa.text("'offline'::device_status_enum"),
               existing_nullable=False)
    op.alter_column('devices', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('devices', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('device_groups', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('api_keys', 'type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
