#!/usr/bin/env python3
"""
scripts/generate_secrets.py
Генерирует все секреты для .env и выводит готовый блок для копирования.

Использование:
    python scripts/generate_secrets.py
    python scripts/generate_secrets.py --output .env.generated

Секреты:
  POSTGRES_PASSWORD  — 32 байта base64url (без padding)
  REDIS_PASSWORD     — 32 байта base64url
  JWT_SECRET_KEY     — 64 байта base64url (512 бит)
  N8N_ENCRYPTION_KEY — 32 байта hex (256 бит)
  AWG_H1..H4         — случайные uint32 (формат AmneziaWG magic headers)
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys
from datetime import datetime, timezone


def b64url(n: int) -> str:
    """n байт в base64url без padding."""
    return secrets.token_urlsafe(n)


def hex_secret(n: int) -> str:
    """n байт в hex."""
    return secrets.token_hex(n)


def awg_header() -> int:
    """Случайный uint32, избегаем 0 и 0xffffffff."""
    while True:
        val = int.from_bytes(os.urandom(4), "big")
        if val not in (0, 0xFFFFFFFF):
            return val


def generate() -> dict[str, str]:
    return {
        "POSTGRES_PASSWORD": b64url(32),
        "REDIS_PASSWORD": b64url(32),
        "JWT_SECRET_KEY": b64url(64),
        "N8N_ENCRYPTION_KEY": hex_secret(32),
        "AWG_H1": str(awg_header()),
        "AWG_H2": str(awg_header()),
        "AWG_H3": str(awg_header()),
        "AWG_H4": str(awg_header()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate sphere-platform secrets")
    parser.add_argument(
        "--output",
        default=None,
        help="Write to file instead of stdout (appends if file exists)",
    )
    args = parser.parse_args()

    secrets_dict = generate()

    lines = [
        f"# Generated by scripts/generate_secrets.py at {datetime.now(timezone.utc).isoformat()}",
        "# NEVER COMMIT THIS FILE",
        "",
    ]
    lines += [f"{k}={v}" for k, v in secrets_dict.items()]
    output = "\n".join(lines) + "\n"

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Secrets written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
