"""Copy the reviewed action contract into the independent frontend build context.

Backend JSON is authoritative. --check is read-only; generated bytes must match,
so neither Docker context requires host source mounts or runtime filesystem access.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "backend/schemas/action_contract.v1.json"
TARGET = ROOT / "frontend/lib/dag/action-contract.v1.json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    # Never propagate malformed edited JSON into the second build context.
    contract = json.loads(raw)
    if contract.get("version") != "1.0" or not isinstance(contract.get("actions"), dict):
        raise ValueError("Unsupported or malformed action contract")
    if args.check:
        if not TARGET.is_file() or TARGET.read_bytes() != raw:
            print("Action contract differs; run python scripts/sync_action_contract.py")
            return 1
        print("Action contract build copies match")
    else:
        TARGET.write_bytes(raw)
        print("Frontend action contract updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
